
export const EnemyStats = {
  goblinRider: {
    name: "Goblin Rider",
    description: "Quick goblin rider, that excels with his agility",
    image: "assets/img/enemies/GoblinRider.png",
    hp: 50,
    speed: 1.5,
    reward: 10,
  },
  camelRider: {
    name: "Camel Rider",
    description: "Fast unit from the desert.",
    image: "assets/img/enemies/CamelRider.png",
    hp: 75,
    speed: 2,
    reward: 15,
  },
  voidling: {
    name: "Voidling",
    description: "I .... am speed.",
    image: "assets/img/enemies/Voidling.png",
    hp: 50,
    speed: 4,
    reward: 8,
  },
  ogre: {
    name: "Ogre",
    description: "Head1: I AM READY<br>Head2: friends call me ogre.",
    image: "assets/img/enemies/Ogre.png",
    hp: 300,
    speed: 0.5,
    reward: 50,
  },
  azog: {
    name: "Azog",
    description: "Mighty warchief of orcs.",
    image: "assets/img/enemies/Azog.png",
    hp: 150,
    speed: 1.2,
    reward: 30,
  },
  lucifer: {
    name: "Lucifer",
    description: "The sending of hell itself",
    image: "assets/img/enemies/Lucifer.png",
    hp: 6666,
    speed: 0.6,
    reward: 666,
  },
};
